sudo: false
language: go
go:
  - "1.14.2"  # use Golang 1.14.2
cache: npm
branches:
  only:
    - google-docsy # build google-docsy branch only
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_extended_0.69.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
script:
  - hugo # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: google-docsy 